directorio<-"C:\\Users\\areasocial\\Documents\\Mesareasocial\\Mesareasocial\\Consultas SGB\\Procedimientos\\Bases actividad egreso genactual\\Area Social y Artistica"
setwd(directorio)
ccee<-read.csv("C:\\Users\\areasocial\\Documents\\Mesareasocial\\Mesareasocial\\Consultas SGB\\Procedimientos\\Bases actividad egreso genactual\\CCEE\\actividad_egresos_85_15_ccee.csv")
fder<-read.csv("C:\\Users\\areasocial\\Documents\\Mesareasocial\\Mesareasocial\\Consultas SGB\\Procedimientos\\Bases actividad egreso genactual\\Derecho\\actividad_egresos_85_15_derecho.csv")
fcs<-read.csv("C:\\Users\\areasocial\\Documents\\Mesareasocial\\Mesareasocial\\Consultas SGB\\Procedimientos\\Bases actividad egreso genactual\\Sociales\\actividad_egresos_85_15_sociales.csv")
fhuce<-read.csv("C:\\Users\\areasocial\\Documents\\Mesareasocial\\Mesareasocial\\Consultas SGB\\Procedimientos\\Bases actividad egreso genactual\\Humanidades\\actividad_egresos_85_15_humanidades.csv")
fic<-read.csv("C:\\Users\\areasocial\\Documents\\Mesareasocial\\Mesareasocial\\Consultas SGB\\Procedimientos\\Bases actividad egreso genactual\\FIC\\actividad_egresos_85_15_FIC.csv")
enba<-read.csv("C:\\Users\\areasocial\\Documents\\Mesareasocial\\Mesareasocial\\Consultas SGB\\Procedimientos\\Bases actividad egreso genactual\\BellasArtes\\actividad_egresos_85_15_bellasartes.csv")
eumus<-read.csv("C:\\Users\\areasocial\\Documents\\Mesareasocial\\Mesareasocial\\Consultas SGB\\Procedimientos\\Bases actividad egreso genactual\\Musica\\actividad_egresos_85_15_musica.csv")
ccee$servicio<-rep("ccee",nrow(ccee))
fder$servicio<-rep("fder",nrow(fder))
fcs$servicio<-rep("fcs",nrow(fcs))
fhuce$servicio<-rep("fhuce",nrow(fhuce))
fic$servicio<-rep("fic",nrow(fic))
enba$servicio<-rep("enba",nrow(enba))
eumus$servicio<-rep("eumus",nrow(eumus))
areasocial<-rbind.data.frame(ccee,fder,fcs,fhuce,fic,enba,eumus)

write.csv(areasocial,"areasocial.csv")
library(foreign)
write.dta(areasocial,"areasocial.dta")