#fusionador area v. 1.0.0
rm(list=ls())
gc()
directorio<-"C:\\Users\\Administrativo\\Documents\\Unidad ASA\\ESENCIALES\\Bases\\Area Social\\Area Social y Artistica"
setwd(directorio)
ccee<-read.csv("C:\\Users\\Administrativo\\Documents\\Unidad ASA\\ESENCIALES\\Bases\\Area Social\\conversion ccee\\actividad_egresos_85_15_ccee.csv")
fder<-read.csv("C:\\Users\\Administrativo\\Documents\\Unidad ASA\\ESENCIALES\\Bases\\Area Social\\conversion fder\\actividad_egresos_85_15_fder.csv")
fcs<-read.csv("C:\\Users\\Administrativo\\Documents\\Unidad ASA\\ESENCIALES\\Bases\\Area Social\\conversion fcs\\actividad_egresos_85_15_fcs.csv")
fhuce<-read.csv("C:\\Users\\Administrativo\\Documents\\Unidad ASA\\ESENCIALES\\Bases\\Area Social\\conversion fhuce\\actividad_egresos_85_15_fhuce.csv")
fic<-read.csv("C:\\Users\\Administrativo\\Documents\\Unidad ASA\\ESENCIALES\\Bases\\Area Social\\conversion fic\\actividad_egresos_85_15_fic.csv")
enba<-read.csv("C:\\Users\\Administrativo\\Documents\\Unidad ASA\\ESENCIALES\\Bases\\Area Social\\conversion enba\\actividad_egresos_85_15_enba.csv")
eumus<-read.csv("C:\\Users\\Administrativo\\Documents\\Unidad ASA\\ESENCIALES\\Bases\\Area Social\\conversion eumus\\actividad_egresos_85_15_eumus.csv")
ccee$servicio<-rep("ccee",nrow(ccee))
fder$servicio<-rep("fder",nrow(fder))
fcs$servicio<-rep("fcs",nrow(fcs))
fhuce$servicio<-rep("fhuce",nrow(fhuce))
fic$servicio<-rep("fic",nrow(fic))
enba$servicio<-rep("enba",nrow(enba))
eumus$servicio<-rep("eumus",nrow(eumus))
areasocial<-rbind.data.frame(ccee,fder,fcs,fhuce,fic,enba,eumus)

write.csv(areasocial,"areasocial_v1_0_0.csv")
library(foreign)
write.dta(areasocial,"areasocial_v1_0_0.dta")